# Generated by Django 4.0.3 on 2022-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('job', models.CharField(max_length=200)),
            ],
        ),
    ]
