# Generated by Django 4.0.3 on 2022-03-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('number', models.CharField(default='', max_length=10)),
                ('ngo', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
