# Generated by Django 4.0.3 on 2022-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_drive_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='prof_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
