# Generated by Django 4.0.3 on 2022-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donate_location_link_alter_donate_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
