# Generated by Django 4.0.3 on 2022-03-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_donate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
