# Generated by Django 4.0.3 on 2022-03-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_alter_donate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
