# Generated by Django 4.0.3 on 2022-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_alter_donate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='apartment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
