# Generated by Django 4.0.3 on 2022-03-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donate_location_link'),
        ('donate', '0007_alter_donate_number'),
    ]

    operations = [
    ]
